---
# Piercing squeekboard layout — generated for github.com/PiercingXX/piercing-keyboard-layout
outlines:
    default:   { width: 35.33, height: 52 }
    altline:   { width: 46, height: 52 }
    wide:      { width: 50, height: 52 }
    special:   { width: 38, height: 52 }
    spaceline: { width: 123.34, height: 52 }

views:
    base:
        - "q r f w g ; l p y z"
        - "a s e t d h n u i o"
        - ", c x v / k m b j ."
        - "Shift_L show_numbers preferences Return space BackSpace"
    upper:
        - "Q R F W G colon L P Y Z"
        - "A S E T D H N U I O"
        - "< C X V ? K M B J >"
        - "Shift_L show_numbers preferences Return space BackSpace"
    numbers:
        - "9 7 5 3 1 0 2 4 6 8"
        - "! @ # $ % ^ & * ( )"
        - "show_symbols - _ + = \" ' colon ?"
        - "show_letters preferences Return space BackSpace"
    symbols:
        - "~ ` | · √ π τ ÷ × ¶"
        - "© ® £ € ¥ ^ ° * { }"
        - "show_numbers_from_symbols \\ / < > = [ ]"
        - "show_letters preferences Return space BackSpace"

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: erase
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "altline"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "wide"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "altline"
        label: "*/="
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "wide"
        icon: "key-enter"
        keysym: "Return"
    colon:
        text: ":"
